apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demoblaze-production
resources:
  - ../../base
  - namespace.yaml
patches:
  - target:
      kind: CronJob
      name: demoblaze-tests
    patch: |-
      - op: replace
        path: /spec/schedule
        value: '0 3 * * 0'
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/args
        value: []
      - op: replace
        path: /spec/jobTemplate/spec/activeDeadlineSeconds
        value: 3600
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/resources/limits/memory
        value: 3Gi
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/resources/limits/cpu
        value: '3'
